### PR TITLE
Fixes

### LINKED ISSUE #4: Migrate to a k6/js.modules.Module (ModulesV2)
## What?

In the k6 [we deprecated](https://github.com/grafana/k6/issues/2344), the usage of the old modules API and in the middle of the process of the migration to a new [ModulesV2 API](https://pkg.go.dev/go.k6.io/k6/js/modules#Module).

To do that, we need to clean up the usages of the deprecated methods:

```code
grep --exclude-dir=vendor -Ri "common.Bind" .
./internal/k8s/k8s.go:	return common.Bind(rt, p, ctx), nil
./internal/experiments/experiments.go:	return common.Bind(rt, p, ctx), nil
```

A good starting point can be our guide [Create an extension](https://k6.io/docs/extensions/guides/create-an-extension/#advanced-javascript-extension).

## Why?

The traditional approach of initializing JS modules involves calling common.Bind() on any objects that need to be exposed to JS. This method has a few technical issues we want to improve and isn't flexible enough to implement new features like giving extensions access to internal k6 objects.

### PR DESCRIPTION
**Pull request by mstoykov**

### CODE REVIEW

**Comment by mstoykov** [comment]
@nicolevanderhoeven please try to run some tests you have with this to be certain it's not completely broken as I don't have a setup to test it.

**Comment by mstoykov** [comment]
This fixes #4

**Review by javaducky — APPROVED** [review]
LGTM. This extension hasn't been getting any love and may be replaced.  Verified the extension can at least be built.

**Comment by javaducky** [comment]
Running the `examples/test.js` fails with the following error:
```
ERRO[0000] TypeError: Value is not an object: undefined
        at killPod (file:///Users/paul/Develop/Extensions/xk6-chaos/examples/test.js:12:20(3))
        at file:///Users/paul/Develop/Extensions/xk6-chaos/examples/test.js:5:2(2)
        at native  executor=per-vu-iterations scenario=default source=stacktrace

running (00m00.0s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [======================================] 1 VUs  00m00.0s/10m0s  1/1 iters, 1 per VU
ERRO[0000] handleSummary() failed with error "TypeError: Value is not an object: undefined", falling back to the default summary  source=console
```
For setup, I created multiple pods, then then modified the script to remove a pod with name containing "new" as shown:
image

I'm not very concerned about this as this extension is _very_ experimental and will likely be abandoned. The recommended method would be to use the `xk6-kubernetes` extension. The custom "chaos" functionality can be done with custom javascript and using the extension strictly for the Kubernetes integration.

**Comment by mstoykov** [comment]
I have made a fixup as this was simply me uppercasing a letter :facepalm:

File: internal/experiments/experiments.go [hunk 1]
```diff
@@ -1,32 +1,48 @@
...
+		Named: map[string]interface{}{
+			"Podkillers": e.XPodkillers,
+		},
+	}
 }
 
 // XPodkillers serves as a constructor of the Podkillers js class
-func (*Experiments) XPodkillers(ctx *context.Context) (interface{}, error) {
-	rt := common.GetRuntime(*ctx)
+func (e *Experiments) XPodkillers(goja.ConstructorCall) goja.Object {
```
Comment (javaducky) [inline internal/experiments/experiments.go]: The return type should be `*goja.Object` otherwise getting error running the script.

File: internal/k8s/k8s.go [hunk 2]
```diff
@@ -1,32 +1,48 @@
...
+		Named: map[string]interface{}{
+			"Pods": k.XPods,
+		},
+	}
+}
+
 // XPods serves as a constructor of the Pods js class
-func (*K8s) XPods(ctx *context.Context) (interface{}, error) {
-	rt := common.GetRuntime(*ctx)
+func (k *K8s) XPods(goja.ConstructorCall) goja.Object {
```
Comment (javaducky) [inline internal/k8s/k8s.go]: This should also be a pointer return, i.e. `*goja.Object`.

**Review by javaducky — CHANGES_REQUESTED** [review]

File: internal/experiments/experiments.go (hunk 1 above)
Comment (mstoykov) [reply internal/experiments/experiments.go]: :facepalm: I likely wrote it wrong from memory and then neovim's autocomplete fixed the type in the return :facepalm:

Thanks :bow:  it's fixed in  [e01e7ca](https://github.com/grafana/xk6-chaos/pull/5/commits/e01e7caf5b7c8b94886a3f09cbb1c8a9687d824d)

File: internal/k8s/k8s.go (hunk 2 above)
Comment (mstoykov) [reply internal/k8s/k8s.go]: see https://github.com/grafana/xk6-chaos/pull/5#discussion_r872090834

**Review by javaducky — APPROVED** [review]
LGTM!  I was able to setup and verify functionality with the `examples/test.js` script.

**Comment by nicolevanderhoeven** [comment]
Thank you @javaducky !! I meant to get around to this but didn't get a chance.
